### ISSUE TITLE
如何修改 vscode preview 中程式碼區塊的顏色？

### ISSUE THREAD

**Issue by errorlog13777** [titangene/hackmd-dark-theme#4]
CSS 苦手，只嘗試出將背景顏色改為黑底，幾經嘗試後程式碼區塊依舊是白底，想請教該修改何處？謝謝。

使用 vscode 的 Markdown Preview Github Styling extension。

**Comment by titangene** [comment]
若你是用 HackMD 的語法，推薦安裝 HackMD 前陣子在 VS Code 推出的 extension：
https://marketplace.visualstudio.com/items?itemName=HackMD.vscode-hackmd

這是我為這個 extension 自訂的暗主題 (內含黑底的程式碼區塊 + highlight，且主題與本 repo 一致)，如有什麼問題都歡迎 PR：
https://github.com/titangene/vscode-hackmd-dark-theme

**Comment by errorlog13777** [comment]
非常謝謝你，這解決了我所有的問題，我愛你 <3
