### ISSUE TITLE
請問有沒有不裝套件的版本

### ISSUE THREAD

**Issue by Tifmin1525Notes** [titangene/hackmd-dark-theme#6]
大大您好，非常謝謝您的努力，辛苦了。
我剛接觸MD的筆記本，想要脫離Evernotes，所以找來找去發現這個HackMD。
但是因為主要的編輯平台是ios和macOS系統的
想知道請問有沒有直接用 {%hackmd noteid %} 來使用Theme的方式。

**Comment by titangene** [comment]
你可參考我在 Blog 「[套用自訂 HackMD 暗主題](https://titangene.github.io/article/hackmd-dark-theme.html#套用暗主題的其他秘訣)」這篇提到的方式來建立自己的 noteid。使用步驟：
1. 建立新筆記
2. 複製 [CSS 樣式原始碼](https://github.com/titangene/hackmd-dark-theme/blob/master/custom.css)
3. 在筆記內容中將複製的 CSS 樣式原始碼放在 `<style>` 的 HTML 元素內
